#!/usr/bin/env python3
"""Generate search/search-notes.js: note/accord tokens per product id,
loaded only by the search page alongside ../list/listing-data.js."""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(HERE, "search-notes.js")


def main():
    with open(os.path.join(REPO_ROOT, "prototype", "list", "listing-data.js")) as f:
        listing = json.loads(f.read().split("=", 1)[1].rstrip().rstrip(";"))["products"]
    ids = {r["id"] for r in listing}

    with open(os.path.join(REPO_ROOT, "enriched-products.json")) as f:
        products = json.load(f)["products"]

    notes = {}
    for p in products:
        pid = p["source"]["id"]
        if pid not in ids:
            continue
        e = p.get("enriched") or {}
        toks = set()
        for field in ("top_notes", "middle_notes", "base_notes", "main_accords"):
            for v in e.get(field) or []:
                v = (v or "").strip().lower()
                if v and v != "n/a":
                    toks.update(v.replace("-", " ").split())
        if toks:
            notes[str(pid)] = ",".join(sorted(toks))

    with open(OUT, "w") as f:
        f.write("// Generated by curate_search.py. Do not edit by hand.\n")
        f.write("window.ODORELITE_NOTES = ")
        json.dump(notes, f, separators=(",", ":"))
        f.write(";\n")
    print(f"products with notes: {len(notes)} / {len(ids)}")
    print(f"wrote {OUT} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
