// Generated by curate.py — do not edit by hand.
window.ODORELITE_DATA = {
 "hero": [
  {
   "id": 10926075510977,
   "brand": "Tom Ford",
   "name": "Lost Cherry",
   "price": 349.0,
   "compareAt": 615.0,
   "discount": 43,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Unisex",
   "accords": [
    "fruity",
    "sweet",
    "nutty"
   ],
   "desc": "A full-bodied journey into the forbidden; a contrasting scent that reveals a tempting dichotomy of playful, candy-like gleam on the outside and luscious flesh on the inside.",
   "img": "../../downloaded-images/10926075510977/hero/1.webp",
   "heroImg": "../../downloaded-images/10926075510977/hero/1.webp"
  },
  {
   "id": 10871610212545,
   "brand": "Creed",
   "name": "Absolu Aventus",
   "price": 444.0,
   "compareAt": 610.0,
   "discount": 27,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Men",
   "accords": [
    "Citrus",
    "Fruity",
    "Woody"
   ],
   "desc": "A limited-edition, denser, and more intense reimagination of the iconic Aventus, featuring a vibrant citrus opening and a smoky, woody base.",
   "img": "../../downloaded-images/10871610212545/hero/1.webp",
   "heroImg": "../../downloaded-images/10871610212545/flacon_detail/7.webp"
  },
  {
   "id": 916409729,
   "brand": "Bond No. 9",
   "name": "Signature",
   "price": 213.0,
   "compareAt": 470.0,
   "discount": 55,
   "concentration": "Pure Perfume",
   "size": "3.4 oz",
   "gender": "Unisex",
   "accords": [
    "Oud",
    "Rose",
    "Musky"
   ],
   "desc": "A seductive, high-concentration oud fragrance created to celebrate the 10th anniversary of the Bond No. 9 headquarters boutique.",
   "img": "../../downloaded-images/916409729/hero/1.jpg",
   "heroImg": "../../downloaded-images/916409729/hero/1.jpg"
  }
 ],
 "promos": [
  {
   "id": 534195393,
   "brand": "Montblanc",
   "name": "Femme Individuelle",
   "price": 25.0,
   "compareAt": 124.0,
   "discount": 80,
   "concentration": "EDT",
   "size": "2.5 oz",
   "gender": "Women",
   "accords": [
    "Warm Spicy",
    "Vanilla",
    "Floral"
   ],
   "desc": "A warm, spicy, and sweet oriental floral fragrance that balances delicate lotus and rose with a base of vanilla and patchouli.",
   "img": "../../downloaded-images/534195393/hero/1.jpg"
  },
  {
   "id": 6826067853505,
   "brand": "Initio Parfums Priv\u00e9s",
   "name": "Oud for Greatness",
   "price": 369.0,
   "compareAt": 410.0,
   "discount": 10,
   "concentration": "EDP",
   "size": "3.04 oz",
   "gender": "Unisex",
   "accords": [
    "Warm Spicy",
    "Oud",
    "Earthy"
   ],
   "desc": "A highly prestigious, sacred scent built around natural oud wood, designed to evoke greatness and harmony.",
   "img": "../../downloaded-images/6826067853505/hero/1.jpg"
  }
 ],
 "dealGrid": [
  {
   "label": "Flash deals under $30",
   "sub": "Big names, tiny prices",
   "product": {
    "id": 10839034691777,
    "brand": "Armaf",
    "name": "Le Parfait Azure Pour Femme",
    "price": 19.0,
    "compareAt": 125.0,
    "discount": 85,
    "concentration": "EDP",
    "size": "3.4 oz",
    "gender": "Women",
    "accords": [],
    "desc": "An Oriental Floral fragrance for women featuring a blend of bright fruits, florals, and a warm, sensual base.",
    "img": "../../downloaded-images/10839034691777/hero/1.webp"
   }
  },
  {
   "label": "70%+ off",
   "sub": "Deepest cuts today",
   "product": {
    "id": 7641146917057,
    "brand": "Afnan",
    "name": "Supremacy Gold",
    "price": 25.0,
    "compareAt": 150.0,
    "discount": 83,
    "concentration": "EDP",
    "size": "3.4 oz",
    "gender": "Men",
    "accords": [
     "Powdery",
     "Warm Spicy",
     "Woody"
    ],
    "desc": "A sophisticated and exclusive fragrance that harmoniously blends floral notes with spiced nuances and a woody, amber base.",
    "img": "../../downloaded-images/7641146917057/hero/1.webp"
   }
  },
  {
   "label": "Niche picks",
   "sub": "Rare & remarkable",
   "product": {
    "id": 7450417823937,
    "brand": "Parfums de Marly",
    "name": "Haltane",
    "price": 369.0,
    "compareAt": 410.0,
    "discount": 10,
    "concentration": "EDP",
    "size": "4.2 oz",
    "gender": "Men",
    "accords": [
     "Woody",
     "Aromatic",
     "Warm Spicy"
    ],
    "desc": "Haltane is an original scent of both radiance and shadow, featuring a blend of rare and noble ingredients that revisit the tradition of 18th-century French perfume making.",
    "img": "../../downloaded-images/7450417823937/hero/1.jpg"
   }
  },
  {
   "label": "Designer classics",
   "sub": "Icons, always in style",
   "product": {
    "id": 10926119157953,
    "brand": "Givenchy",
    "name": "L'Interdit Parfum",
    "price": 95.0,
    "compareAt": 196.0,
    "discount": 52,
    "concentration": "Parfum",
    "size": "2.7 oz",
    "gender": "Women",
    "accords": [
     "White Floral",
     "Woody",
     "Amber"
    ],
    "desc": "L'Interdit Parfum captures audacious elegance in a bottle, featuring a signature white floral bouquet contrasted with deep, woody-ambery notes.",
    "img": "../../downloaded-images/10926119157953/hero/1.webp"
   }
  },
  {
   "label": "Arabian house gems",
   "sub": "Lattafa, Armaf & more",
   "product": {
    "id": 7641147375809,
    "brand": "Afnan",
    "name": "Supremacy Purple",
    "price": 25.0,
    "compareAt": 150.0,
    "discount": 83,
    "concentration": "EDP",
    "size": "3.4 oz",
    "gender": "Women",
    "accords": [
     "Fruity",
     "Floral",
     "Musky"
    ],
    "desc": "A feminine fragrance featuring a blend of fruity top notes, a floral heart, and a warm, musky base.",
    "img": "../../downloaded-images/7641147375809/hero/1.jpg"
   }
  },
  {
   "label": "New arrivals",
   "sub": "Fresh on the shelf",
   "product": {
    "id": 9663727553,
    "brand": "Creed",
    "name": "Aventus",
    "price": 339.0,
    "compareAt": 510.0,
    "discount": 34,
    "concentration": "EDP",
    "size": "3.3 oz",
    "gender": "Men",
    "accords": [
     "Fruity",
     "Sweet",
     "Leather"
    ],
    "desc": "A legendary fruity-chypre fragrance that balances pineapple and bergamot with a smoky birch base, designed to evoke strength and success.",
    "img": "../../downloaded-images/9663727553/hero/1.webp"
   }
  }
 ],
 "dealsRail": [
  {
   "id": 7641147277505,
   "brand": "Afnan",
   "name": "Supremacy Pink",
   "price": 25.0,
   "compareAt": 150.0,
   "discount": 83,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Women",
   "accords": [
    "Floral",
    "Musky",
    "Rose"
   ],
   "desc": "Supremacy Pink is a luxurious, harmonious EDP for women featuring an alluring blend of floral and musk notes.",
   "img": "../../downloaded-images/7641147277505/hero/1.webp"
  },
  {
   "id": 6954336092353,
   "brand": "New Brand",
   "name": "Ego Gold",
   "price": 11.0,
   "compareAt": 65.0,
   "discount": 83,
   "concentration": "EDT",
   "size": "3.3 oz",
   "gender": "Men",
   "accords": [
    "Citrus",
    "Leather",
    "Warm Spicy"
   ],
   "desc": "A masculine fragrance featuring a blend of citrus, mint, rose, and leather notes.",
   "img": "../../downloaded-images/6954336092353/hero/1.png"
  },
  {
   "id": 10894764802241,
   "brand": "New Brand",
   "name": "Prestige Y",
   "price": 12.0,
   "compareAt": 65.0,
   "discount": 82,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Unisex",
   "accords": [],
   "desc": "New Brand Prestige Y is a sophisticated floral eau de parfum blending fresh, orris, and powdery notes with elemi, amber, sandalwood, and musk.",
   "img": "../../downloaded-images/10894764802241/hero/1.webp"
  },
  {
   "id": 7410469503169,
   "brand": "Orientica",
   "name": "XO Xclusif Oud Emerald",
   "price": 48.0,
   "compareAt": 250.0,
   "discount": 81,
   "concentration": "EDP",
   "size": "2.7 oz",
   "gender": "Unisex",
   "accords": [
    "Woody",
    "Warm Spicy",
    "Citrus"
   ],
   "desc": "A sophisticated and bold woody amber fragrance designed for those who appreciate a rich, complex scent profile.",
   "img": "../../downloaded-images/7410469503169/hero/1.webp"
  },
  {
   "id": 10925299368129,
   "brand": "Jaguar",
   "name": "Vision Sport",
   "price": 16.0,
   "compareAt": 79.0,
   "discount": 80,
   "concentration": "EDT",
   "size": "3.4 oz",
   "gender": "Men",
   "accords": [
    "Citrus",
    "Woody",
    "White Floral"
   ],
   "desc": "Jaguar Vision Sport is a sophisticated woody floral musk fragrance for men, featuring a vibrant citrus opening and a refined floral-woody base.",
   "img": "../../downloaded-images/10925299368129/hero/1.webp"
  },
  {
   "id": 10871590813889,
   "brand": "Al Haramain",
   "name": "L'Aventure Gold",
   "price": 41.0,
   "compareAt": 210.0,
   "discount": 80,
   "concentration": "EDP",
   "size": "6.8 oz",
   "gender": "Women",
   "accords": [
    "Floral",
    "Woody",
    "Musky"
   ],
   "desc": "L'Aventure Gold by Al Haramain Perfumes captures the essence of refined femininity with its sophisticated Floral Woody Musk composition.",
   "img": "../../downloaded-images/10871590813889/hero/1.webp"
  },
  {
   "id": 10695434698945,
   "brand": "786 Parfum Dubai",
   "name": "Qatar King",
   "price": 32.0,
   "compareAt": 160.0,
   "discount": 80,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Men",
   "accords": [],
   "desc": "Experience the ultimate power and sophistication with Qatar King EDP for men. Crafted for the modern gentleman, this bold and refined scent commands attention effortlessly.",
   "img": "../../downloaded-images/10695434698945/hero/1.webp"
  },
  {
   "id": 6203906883777,
   "brand": "Cuba Paris",
   "name": "Cuba Grey",
   "price": 4.0,
   "compareAt": 20.0,
   "discount": 80,
   "concentration": "EDT",
   "size": "1.17 oz",
   "gender": "Men",
   "accords": [
    "Woody",
    "Lavender",
    "Aromatic"
   ],
   "desc": "A woody aromatic fragrance for men, known for its blend of vetiver, lavender, and woods, often compared to classic 90s fresh foug\u00e8res.",
   "img": "../../downloaded-images/6203906883777/hero/1.jpg"
  },
  {
   "id": 4743295828056,
   "brand": "Yzy",
   "name": "Black Point Sport",
   "price": 12.0,
   "compareAt": 60.0,
   "discount": 80,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Men",
   "accords": [],
   "desc": "A men's fragrance by YZY Perfumes.",
   "img": "../../downloaded-images/4743295828056/hero/1.jpg"
  },
  {
   "id": 1359882190936,
   "brand": "Parfums des Champs",
   "name": "Cuba Winner",
   "price": 4.0,
   "compareAt": 20.0,
   "discount": 80,
   "concentration": "EDT",
   "size": "1.17 oz",
   "gender": "Men",
   "accords": [],
   "desc": "An aquatic, woody fragrance that blends the excitement of sport with elements of victory and power.",
   "img": "../../downloaded-images/1359882190936/hero/1.jpg"
  },
  {
   "id": 2159189057,
   "brand": "Cuba Paris",
   "name": "Cuba Red",
   "price": 4.0,
   "compareAt": 20.0,
   "discount": 80,
   "concentration": "EDT",
   "size": "1.17 oz",
   "gender": "Men",
   "accords": [
    "Woody",
    "Tobacco",
    "Mossy"
   ],
   "desc": "Cuba Red is a fiery and masculine fragrance, blending exotic woods, mosses, raw tobacco and spicy notes.",
   "img": "../../downloaded-images/2159189057/hero/1.jpg"
  },
  {
   "id": 10922920739009,
   "brand": "Maison Alhambra",
   "name": "Victorioso Heroic",
   "price": 16.0,
   "compareAt": 75.0,
   "discount": 79,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Men",
   "accords": [],
   "desc": "A bold aromatic fragrance featuring notes of violet, lavender, geranium, cedarwood, tonka bean, and sandalwood.",
   "img": "../../downloaded-images/10922920739009/hero/1.webp"
  }
 ],
 "trendingRail": [
  {
   "id": 10678021718209,
   "brand": "Dolce & Gabbana",
   "name": "K by D&G Parfum",
   "price": 71.0,
   "compareAt": 190.0,
   "discount": 63,
   "concentration": "Parfum",
   "size": "3.3 oz",
   "gender": "Men",
   "accords": [
    "Woody",
    "Sweet",
    "Fruity"
   ],
   "desc": "A bold and sophisticated woody-spicy fragrance that reimagines the signature fig note of the K collection as a rich, caramelized accord, balanced by licorice and a warm sandalwood base.",
   "img": "../../downloaded-images/10678021718209/hero/1.webp"
  },
  {
   "id": 10930351341761,
   "brand": "Jean Paul Gaultier",
   "name": "Gaultier Divine Le Parfum",
   "price": 119.0,
   "compareAt": 185.0,
   "discount": 36,
   "concentration": "Le Parfum",
   "size": "3.4 oz",
   "gender": "Women",
   "accords": [
    "Amber",
    "Floral",
    "Solar"
   ],
   "desc": "A more intense, solar, and floral interpretation of the original Gaultier Divine, featuring notes of solar flowers, frangipani, and benzoin.",
   "img": "../../downloaded-images/10930351341761/flacon_detail/6.webp"
  },
  {
   "id": 6790359220417,
   "brand": "Carolina Herrera",
   "name": "Very Good Girl",
   "price": 110.0,
   "compareAt": 184.0,
   "discount": 40,
   "concentration": "EDP",
   "size": "2.7 oz",
   "gender": "Women",
   "accords": [
    "Fruity",
    "Rose",
    "Tropical"
   ],
   "desc": "A bold and playful floral fruity fragrance featuring notes of lychee, rose, and vanilla.",
   "img": "../../downloaded-images/6790359220417/hero/1.jpg"
  },
  {
   "id": 10930355208385,
   "brand": "Rabanne",
   "name": "Million Gold Elixir",
   "price": 90.0,
   "compareAt": 182.0,
   "discount": 51,
   "concentration": "Parfum Intense",
   "size": "3.4 oz",
   "gender": "Men",
   "accords": [
    "Woody",
    "Vanilla",
    "Citrus"
   ],
   "desc": "A powerful and intense fragrance featuring a blend of yellow mandarin, cedar, and addictive vanilla, designed for the man who commands attention.",
   "img": "../../downloaded-images/10930355208385/hero/1.webp"
  },
  {
   "id": 6972568010945,
   "brand": "Gucci",
   "name": "Guilty Eau de Toilette",
   "price": 74.0,
   "compareAt": 181.0,
   "discount": 59,
   "concentration": "EDT",
   "size": "3.0 oz",
   "gender": "Women",
   "accords": [
    "Floral",
    "Citrus",
    "Fresh Spicy"
   ],
   "desc": "A bold and modern amber floral fragrance that blends citrus and pink pepper with a heart of lilac and a warm, sensual base of patchouli and amber.",
   "img": "../../downloaded-images/6972568010945/hero/1.jpg"
  },
  {
   "id": 4797173235800,
   "brand": "Carolina Herrera",
   "name": "Good Girl",
   "price": 137.0,
   "compareAt": 180.0,
   "discount": 24,
   "concentration": "EDP",
   "size": "5.1 oz",
   "gender": "Women",
   "accords": [
    "White Floral",
    "Warm Spicy",
    "Sweet"
   ],
   "desc": "A daring and sophisticated fragrance that captures the duality of the modern woman, blending sweet floral notes with deep, dark gourmand elements.",
   "img": "../../downloaded-images/4797173235800/hero/1.jpg"
  },
  {
   "id": 7495469039809,
   "brand": "Prada",
   "name": "Paradoxe",
   "price": 119.0,
   "compareAt": 180.0,
   "discount": 34,
   "concentration": "EDP",
   "size": "3.0 oz",
   "gender": "Women",
   "accords": [
    "Citrus",
    "White Floral",
    "Vanilla"
   ],
   "desc": "A floral ambery fragrance that embraces the paradoxes of iconic ingredients, balancing freshness with vibrant warmth.",
   "img": "../../downloaded-images/7495469039809/hero/1.webp"
  },
  {
   "id": 7001611239617,
   "brand": "Valentino",
   "name": "Donna Born In Roma",
   "price": 129.0,
   "compareAt": 180.0,
   "discount": 28,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Women",
   "accords": [
    "Vanilla",
    "White Floral",
    "Amber"
   ],
   "desc": "A modern haute couture floriental fragrance blending three types of jasmine with a warm Bourbon vanilla accord.",
   "img": "../../downloaded-images/7001611239617/hero/1.jpg"
  },
  {
   "id": 534197121,
   "brand": "Burberry",
   "name": "My Burberry",
   "price": 65.0,
   "compareAt": 180.0,
   "discount": 64,
   "concentration": "EDP",
   "size": "3.0 oz",
   "gender": "Women",
   "accords": [
    "Floral",
    "Rose",
    "Fresh"
   ],
   "desc": "A floral fragrance inspired by a London garden after the rain and the iconic Burberry trench coat.",
   "img": "../../downloaded-images/534197121/hero/1.jpg"
  },
  {
   "id": 10710711959745,
   "brand": "Dolce & Gabbana",
   "name": "Light Blue Capri In Love Eau de Parfum",
   "price": 58.0,
   "compareAt": 179.0,
   "discount": 68,
   "concentration": "EDP",
   "size": "3.4 oz",
   "gender": "Women",
   "accords": [
    "Floral",
    "Fruity",
    "Spicy"
   ],
   "desc": "A floral fruity fragrance for women inspired by the landscapes of Capri, featuring notes of jasmine tea, apple, and longoza.",
   "img": "../../downloaded-images/10710711959745/hero/1.webp"
  },
  {
   "id": 10925174030529,
   "brand": "Giorgio Armani",
   "name": "My Way Nectar",
   "price": 104.0,
   "compareAt": 170.0,
   "discount": 39,
   "concentration": "EDP",
   "size": "3.0 oz",
   "gender": "Women",
   "accords": [
    "White Floral",
    "Fruity",
    "Sweet"
   ],
   "desc": "A radiant and fruity floral fragrance that captures a sparkling, addictive nectar.",
   "img": "../../downloaded-images/10925174030529/hero/1.jpg"
  },
  {
   "id": 10728590049473,
   "brand": "Paco Rabanne",
   "name": "Phantom Elixir",
   "price": 93.0,
   "compareAt": 170.0,
   "discount": 45,
   "concentration": "Parfum Intense",
   "size": "3.4 oz",
   "gender": "Men",
   "accords": [
    "Woody",
    "Aquatic",
    "Vanilla"
   ],
   "desc": "A woody-aquatic fragrance capturing the rock and roll spirit with a fresh marine accord, vibrant mineral oud, and warm vanilla bean.",
   "img": "../../downloaded-images/10728590049473/hero/1.webp"
  }
 ],
 "nicheRail": [
  {
   "id": 2096416981080,
   "brand": "Parfums de Marly",
   "name": "Delina Exclusif",
   "price": 337.5,
   "compareAt": 395.0,
   "discount": 15,
   "concentration": "EDP",
   "size": "2.5 oz",
   "gender": "Women",
   "accords": [
    "Rose",
    "Powdery",
    "Vanilla"
   ],
   "desc": "A deeper, more intense interpretation of the original Delina, featuring a rich blend of Turkish rose, incense, and vanilla.",
   "img": "../../downloaded-images/2096416981080/hero/1.webp"
  },
  {
   "id": 6825647079617,
   "brand": "Initio",
   "name": "Rehab",
   "price": 337.0,
   "compareAt": 370.0,
   "discount": 9,
   "concentration": "Extrait de Parfum",
   "size": "3.04 oz",
   "gender": "Unisex",
   "accords": [
    "Woody",
    "Aromatic",
    "Earthy"
   ],
   "desc": "A sweet-yet-smoky, woody aromatic fragrance that acts as a sensory sanctuary, balancing lavender and spices with a creamy, woody base.",
   "img": "../../downloaded-images/6825647079617/hero/1.jpg"
  },
  {
   "id": 401105649704,
   "brand": "Parfums de Marly",
   "name": "Delina",
   "price": 319.5,
   "compareAt": 410.0,
   "discount": 22,
   "concentration": "EDP",
   "size": "2.5 oz",
   "gender": "Women",
   "accords": [
    "Rose",
    "Floral",
    "Fresh"
   ],
   "desc": "A modern floral fragrance characterized by a dominant Turkish rose note, brightened by lychee and rhubarb, and grounded by a soft, woody base.",
   "img": "../../downloaded-images/401105649704/hero/1.webp"
  },
  {
   "id": 4694183379032,
   "brand": "Parfums de Marly",
   "name": "Godolphin",
   "price": 315.0,
   "compareAt": 365.0,
   "discount": 14,
   "concentration": "EDP",
   "size": "4.2 oz",
   "gender": "Men",
   "accords": [
    "Leather",
    "Warm Spicy",
    "Aromatic"
   ],
   "desc": "A distinguished leather scent inspired by the regal Godolphin stallion, balancing rich leather with spicy, floral, and woody notes.",
   "img": "../../downloaded-images/4694183379032/hero/1.webp"
  },
  {
   "id": 6825651404993,
   "brand": "Initio Parfums Priv\u00e9s",
   "name": "Side Effect",
   "price": 299.0,
   "compareAt": 360.0,
   "discount": 17,
   "concentration": "EDP",
   "size": "3.04 oz",
   "gender": "Unisex",
   "accords": [
    "Warm Spicy",
    "Vanilla",
    "Tobacco"
   ],
   "desc": "A spellbinding, intoxicating blend of tobacco, vanilla, rum, and cinnamon designed to evoke deep emotions and passions.",
   "img": "../../downloaded-images/6825651404993/hero/1.jpg"
  },
  {
   "id": 9663728321,
   "brand": "Creed",
   "name": "Silver Mountain Water",
   "price": 259.0,
   "compareAt": 490.0,
   "discount": 47,
   "concentration": "EDP",
   "size": "3.3 oz",
   "gender": "Men",
   "accords": [
    "Musky",
    "Green",
    "Fresh"
   ],
   "desc": "A crisp, refreshing fragrance inspired by the sparkling streams of the Swiss Alps, featuring notes of green tea and black currant.",
   "img": "../../downloaded-images/9663728321/hero/1.jpg"
  },
  {
   "id": 441425821736,
   "brand": "Creed",
   "name": "Green Irish Tweed",
   "price": 249.0,
   "compareAt": 490.0,
   "discount": 49,
   "concentration": "EDP",
   "size": "3.3 oz",
   "gender": "Men",
   "accords": [
    "Green",
    "Violet",
    "Citrus"
   ],
   "desc": "A classic, sophisticated fragrance that captures the essence of the Irish countryside with a blend of fresh green notes and refined woods.",
   "img": "../../downloaded-images/441425821736/hero/1.webp"
  },
  {
   "id": 8189307649,
   "brand": "Creed",
   "name": "Aventus for Her",
   "price": 249.0,
   "compareAt": 460.0,
   "discount": 46,
   "concentration": "EDP",
   "size": "2.5 oz",
   "gender": "Women",
   "accords": [
    "Fruity",
    "Fresh",
    "Woody"
   ],
   "desc": "An empowering, confident, and mesmerizing fruity-fresh fragrance designed for the modern woman, serving as the feminine counterpart to the legendary Aventus.",
   "img": "../../downloaded-images/8189307649/hero/1.webp"
  }
 ],
 "buckets": [
  {
   "label": "Gifts under $25",
   "cap": 25,
   "products": [
    {
     "id": 10894767227073,
     "brand": "New Brand",
     "name": "Phantom",
     "price": 12.0,
     "compareAt": 65.0,
     "discount": 82,
     "concentration": "EDP",
     "size": "3.4 oz",
     "gender": "Women",
     "accords": [
      "White Floral",
      "Amber",
      "Woody"
     ],
     "desc": "A budget-friendly fragrance inspired by Thierry Mugler Alien, featuring a prominent jasmine, wood, and amber profile.",
     "img": "../../downloaded-images/10894767227073/hero/1.webp"
    },
    {
     "id": 6721686929601,
     "brand": "New Brand",
     "name": "NB Fluo Pink",
     "price": 12.0,
     "compareAt": 60.0,
     "discount": 80,
     "concentration": "EDP",
     "size": "3.4 oz",
     "gender": "Women",
     "accords": [],
     "desc": "A women's fragrance by New Brand.",
     "img": "../../downloaded-images/6721686929601/hero/1.jpg"
    },
    {
     "id": 2159184065,
     "brand": "Cuba Paris",
     "name": "Cuba Blue",
     "price": 4.0,
     "compareAt": 20.0,
     "discount": 80,
     "concentration": "EDT",
     "size": "1.17 oz",
     "gender": "Men",
     "accords": [
      "Woody",
      "Warm Spicy",
      "Musky"
     ],
     "desc": "Cuba Blue is a fresh, woody fragrance for men, characterized by its iconic cigar-shaped bottle design.",
     "img": "../../downloaded-images/2159184065/hero/1.jpg"
    },
    {
     "id": 2159183553,
     "brand": "Cuba Paris",
     "name": "Cuba Black",
     "price": 4.0,
     "compareAt": 20.0,
     "discount": 80,
     "concentration": "EDT",
     "size": "1.17 oz",
     "gender": "Men",
     "accords": [
      "Aromatic",
      "Citrus",
      "Woody"
     ],
     "desc": "Cuba Black is a romantic and sensual fragrance for men, blending rich jasmine with sparkling bergamot, citruses, and woods.",
     "img": "../../downloaded-images/2159183553/hero/1.jpg"
    }
   ]
  },
  {
   "label": "Gifts under $50",
   "cap": 50,
   "products": [
    {
     "id": 7129382453441,
     "brand": "Lalique",
     "name": "Perles De Lalique",
     "price": 36.0,
     "compareAt": 175.0,
     "discount": 79,
     "concentration": "EDP",
     "size": "3.4 oz",
     "gender": "Women",
     "accords": [
      "Rose",
      "Patchouli",
      "Earthy"
     ],
     "desc": "A sophisticated and minimalist Chypre Floral fragrance centered around a spicy, peppery rose and earthy patchouli.",
     "img": "../../downloaded-images/7129382453441/hero/1.jpg"
    },
    {
     "id": 9208683841,
     "brand": "Lalique",
     "name": "L'Amour",
     "price": 37.0,
     "compareAt": 176.0,
     "discount": 79,
     "concentration": "EDP",
     "size": "3.3 oz",
     "gender": "Women",
     "accords": [
      "White Floral",
      "Citrus",
      "Woody"
     ],
     "desc": "A sophisticated and romantic floral woody musk fragrance inspired by the eternal allure of femininity.",
     "img": "../../downloaded-images/9208683841/hero/1.jpg"
    },
    {
     "id": 10908413100225,
     "brand": "Jo Milano",
     "name": "Game of Spades Royale",
     "price": 33.0,
     "compareAt": 150.0,
     "discount": 78,
     "concentration": "Parfum",
     "size": "1.0 oz",
     "gender": "Unisex",
     "accords": [],
     "desc": "An unisex parfum with an inviting aroma of hazelnut and cacao top notes layered with jasmine sambac, cedar, caramel, ambroxan, and moss.",
     "img": "../../downloaded-images/10908413100225/hero/1.webp"
    },
    {
     "id": 10114655584449,
     "brand": "Afnan",
     "name": "Turathi Blue",
     "price": 35.0,
     "compareAt": 150.0,
     "discount": 77,
     "concentration": "EDP",
     "size": "3.0 oz",
     "gender": "Men",
     "accords": [
      "Citrus",
      "Amber",
      "Musky"
     ],
     "desc": "A refreshing and sophisticated aromatic citrus fragrance for men, known for its high-quality blend and resemblance to luxury niche scents.",
     "img": "../../downloaded-images/10114655584449/hero/1.webp"
    }
   ]
  },
  {
   "label": "Gifts under $100",
   "cap": 100,
   "products": [
    {
     "id": 10867612385473,
     "brand": "Jo Milano",
     "name": "Game Of Spades Double Bonus",
     "price": 69.0,
     "compareAt": 320.0,
     "discount": 78,
     "concentration": "Parfum",
     "size": "3.4 oz",
     "gender": "Unisex",
     "accords": [],
     "desc": "A refined unisex Parfum that merges audacious character with understated elegance, delivering sustained projection and depth.",
     "img": "../../downloaded-images/10867612385473/hero/1.webp"
    },
    {
     "id": 10647970775233,
     "brand": "Jo Milano",
     "name": "Game Of Spades Opal",
     "price": 70.0,
     "compareAt": 320.0,
     "discount": 78,
     "concentration": "Parfum",
     "size": "3.4 oz",
     "gender": "Unisex",
     "accords": [
      "Floral",
      "Fruity",
      "Woody"
     ],
     "desc": "A sophisticated and alluring unisex fragrance featuring a bright, fruity opening of raspberry and pear, a floral heart, and a smooth, woody-musky base.",
     "img": "../../downloaded-images/10647970775233/hero/1.webp"
    },
    {
     "id": 6832655007937,
     "brand": "Orientica",
     "name": "Cuir de Orientica Edition Noir",
     "price": 55.0,
     "compareAt": 250.0,
     "discount": 78,
     "concentration": "EDP",
     "size": "3.4 oz",
     "gender": "Men",
     "accords": [
      "Leather",
      "Amber",
      "Woody"
     ],
     "desc": "A sophisticated and bold leather-forward fragrance with woody and spicy undertones.",
     "img": "../../downloaded-images/6832655007937/hero/1.jpg"
    },
    {
     "id": 10112625049793,
     "brand": "Jo Milano Paris",
     "name": "Game of Spades Blind-Bid",
     "price": 75.0,
     "compareAt": 320.0,
     "discount": 77,
     "concentration": "Parfum",
     "size": "3.4 oz",
     "gender": "Unisex",
     "accords": [],
     "desc": "A citrus-woody unisex fragrance featuring a blend of bergamot, spices, and earthy base notes.",
     "img": "../../downloaded-images/10112625049793/hero/1.webp"
    }
   ]
  }
 ],
 "categories": [
  {
   "label": "Women",
   "count": 2284,
   "img": "../../downloaded-images/6790359220417/hero/1.jpg"
  },
  {
   "label": "Men",
   "count": 1901,
   "img": "../../downloaded-images/9663727553/hero/1.webp"
  },
  {
   "label": "Unisex",
   "count": 804,
   "img": "../../downloaded-images/6826067853505/hero/1.jpg"
  },
  {
   "label": "Niche",
   "count": 537,
   "img": "../../downloaded-images/401105977384/hero/1.webp"
  }
 ],
 "brands": [
  "Tom Ford",
  "Kilian",
  "Bond No. 9",
  "Carolina Herrera",
  "Dolce & Gabbana",
  "Paco Rabanne",
  "Montale",
  "Lattafa"
 ],
 "guides": [
  {
   "tag": "Guide",
   "title": "How to choose your signature scent",
   "excerpt": "Fragrance families, skin chemistry, and the three questions that narrow 5,000 bottles to one.",
   "img": "../../downloaded-images/2096416981080/hero/1.webp"
  },
  {
   "tag": "Explained",
   "title": "EDT vs EDP: what concentration really means",
   "excerpt": "Why the same fragrance lasts 3 hours in one bottle and 8 in another \u2014 and which is right for you.",
   "img": "../../downloaded-images/6825647079617/hero/1.jpg"
  },
  {
   "tag": "Technique",
   "title": "Layering 101: build a scent no one else wears",
   "excerpt": "Pairing rules the pros use: anchor with woods, lift with citrus, never double the same accord.",
   "img": "../../downloaded-images/6825651404993/hero/1.jpg"
  }
 ]
};
