#!/usr/bin/env python3
"""Generate brands/brands-data.js — one record per brand for the brand index
and brand pages: counts, niche flag, representative image, story excerpt."""

import importlib.util
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(HERE, "brands-data.js")

_spec = importlib.util.spec_from_file_location(
    "home_curate", os.path.join(REPO_ROOT, "prototype", "home", "curate.py"))
home = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(home)
NICHE_UPPER = {h.upper() for h in home.NICHE_HOUSES}


def main():
    with open(os.path.join(REPO_ROOT, "prototype", "list", "listing-data.js")) as f:
        listing = json.loads(f.read().split("=", 1)[1].rstrip().rstrip(";"))["products"]

    with open(os.path.join(REPO_ROOT, "enriched-products.json")) as f:
        products = json.load(f)["products"]
    story_by_id = {}
    for p in products:
        e = p.get("enriched") or {}
        s = (e.get("brand_story") or "").strip()
        if s and s.upper() != "N/A":
            story_by_id[p["source"]["id"]] = s

    brands = {}
    for r in listing:
        b = brands.setdefault(r["brand"], {
            "name": r["brand"], "count": 0, "inStock": 0, "niche": 0,
            "img": None, "imgDiscount": -1, "story": "", "maxOff": 0,
        })
        b["count"] += 1
        b["inStock"] += 1 if r["avail"] else 0
        b["maxOff"] = max(b["maxOff"], r["discount"])
        if r["niche"]:
            b["niche"] = 1
        # representative image: best-discount in-stock product's image
        rank = r["discount"] + (100 if r["avail"] else 0)
        if rank > b["imgDiscount"]:
            b["imgDiscount"] = rank
            b["img"] = r["img"]
        if not b["story"] and r["id"] in story_by_id:
            s = story_by_id[r["id"]]
            b["story"] = s[:240].rsplit(" ", 1)[0] + ("…" if len(s) > 240 else "")

    out = sorted(
        ({k: v for k, v in b.items() if k != "imgDiscount"} for b in brands.values()),
        key=lambda b: b["name"].lower()
    )

    with open(OUT, "w") as f:
        f.write("// Generated by curate_brands.py. Do not edit by hand.\n")
        f.write("window.ODORELITE_BRANDS = ")
        json.dump(out, f, separators=(",", ":"))
        f.write(";\n")
    niche_ct = sum(1 for b in out if b["niche"])
    print(f"brands: {len(out)} | niche: {niche_ct} | with story: {sum(1 for b in out if b['story'])}")
    print(f"wrote {OUT} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
